// <auto-generated />
namespace CatDatingSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class madecatnamerequiredBecauseiwantedto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madecatnamerequiredBecauseiwantedto));
        
        string IMigrationMetadata.Id
        {
            get { return "201801041828350_made catname required. Because i wanted to."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
