// <auto-generated />
namespace CatDatingSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedfiles2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfiles2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801051829515_added files2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
